# Generated by Django 5.0.1 on 2024-01-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_options_alter_product_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(null=True),
        ),
    ]
