# Generated by Django 5.0.1 on 2024-01-16 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_bill_options_alter_billproducts_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billproducts',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bill'),
        ),
        migrations.AlterField(
            model_name='billproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
