# Generated by Django 5.0.1 on 2024-01-12 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_description', models.TextField()),
                ('price', models.FloatField()),
                ('unit', models.CharField(choices=[('kg', 'kilogram'), ('piece', 'ştuk')], max_length=5)),
                ('count_in_stock', models.IntegerField()),
                ('total_price', models.FloatField(default=0)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
    ]
