# Generated by Django 5.0.1 on 2024-01-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Haryt', 'verbose_name_plural': 'Harytlar'},
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
